'use client';

import { Suspense, useEffect, useState, useRef } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import {
  ArrowLeft,
  Sparkles,
  ThumbsUp,
  AlertCircle,
  Lightbulb,
  Loader2,
  Users,
  ClipboardList,
  CheckCircle2,
  PercentCircle,
} from 'lucide-react';

interface Summary {
  id: string;
  strengths: string;
  weaknesses: string;
  suggestions: string;
  question_total: number;
  question_correct: number;
  discussion_summary: string;
  overall_summary: string;
  created_at: string;
}

interface StudentUser {
  id: string;
  name: string;
  role: string;
}

function StudentSummaryContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [user, setUser] = useState<StudentUser | null>(null);
  const [summary, setSummary] = useState<Summary | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');

  // Streaming state
  const [streamingStrengths, setStreamingStrengths] = useState('');
  const [streamingWeaknesses, setStreamingWeaknesses] = useState('');
  const [streamingSuggestions, setStreamingSuggestions] = useState('');
  const [streamingDiscussion, setStreamingDiscussion] = useState('');
  const [streamingOverall, setStreamingOverall] = useState('');
  const [isStreaming, setIsStreaming] = useState(false);

  const abortRef = useRef<AbortController | null>(null);
  const hasAutoGeneratedRef = useRef(false);

  useEffect(() => {
    const token = localStorage.getItem('student_token');
    const userData = localStorage.getItem('student_user');
    if (!token || !userData) {
      router.push('/student/login');
      return;
    }
    setUser(JSON.parse(userData));
    fetchSummary();
  }, [router]);

  // Auto-generate if no summary exists, or if regenerate=true from chat page
  useEffect(() => {
    if (!loading && !isStreaming && !generating && !hasAutoGeneratedRef.current) {
      const shouldRegenerate = searchParams.get('regenerate') === 'true';
      
      if (!summary) {
        // No summary exists, auto-generate
        hasAutoGeneratedRef.current = true;
        generateSummary();
      } else if (shouldRegenerate) {
        // Explicitly requested regeneration from chat page
        hasAutoGeneratedRef.current = true;
        generateSummary();
      }
      // If summary exists and no regenerate param, just show it (don't regenerate)
    }
  }, [loading, summary, isStreaming, generating]);

  const fetchSummary = async () => {
    try {
      const userData = localStorage.getItem('student_user');
      if (!userData) return;
      const parsedUser = JSON.parse(userData);

      const res = await fetch(`/api/summary?student_id=${parsedUser.id}`);
      const data = await res.json();
      setSummary(data.data || null);
    } catch (err) {
      console.error('Fetch error:', err);
    } finally {
      setLoading(false);
    }
  };

  const generateSummary = async () => {
    // Abort previous stream if any
    if (abortRef.current) {
      abortRef.current.abort();
    }

    setGenerating(true);
    setError('');
    setStreamingStrengths('');
    setStreamingWeaknesses('');
    setStreamingSuggestions('');
    setStreamingDiscussion('');
    setStreamingOverall('');
    setIsStreaming(true);

    try {
      const userData = localStorage.getItem('student_user');
      if (!userData) return;
      const parsedUser = JSON.parse(userData);

      // Get the latest session from interactions
      const interRes = await fetch(`/api/interactions?student_id=${parsedUser.id}`);
      const interData = await interRes.json();
      const interactions = interData.data || [];

      if (interactions.length === 0) {
        setError('暂无互动记录，请先与智能体进行对话学习');
        setGenerating(false);
        setIsStreaming(false);
        return;
      }

      // Get the latest session ID
      const latestSessionId = interactions[interactions.length - 1].session_id;

      const abortController = new AbortController();
      abortRef.current = abortController;

      const res = await fetch('/api/summary', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          student_id: parsedUser.id,
          session_id: latestSessionId,
        }),
        signal: abortController.signal,
      });

      if (!res.ok) {
        const errorData = await res.json();
        setError(errorData.error || '生成失败');
        setGenerating(false);
        setIsStreaming(false);
        return;
      }

      // Read SSE stream
      const reader = res.body?.getReader();
      if (!reader) {
        setError('无法读取响应流');
        setGenerating(false);
        setIsStreaming(false);
        return;
      }

      const decoder = new TextDecoder();
      let buffer = '';
      let fullContent = '';

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });

        // Process SSE events
        const lines = buffer.split('\n');
        buffer = lines.pop() || ''; // Keep incomplete line in buffer

        for (const line of lines) {
          if (line.startsWith('data: ')) {
            const data = line.slice(6).trim();

            if (data === '[DONE]') {
              continue;
            }

            try {
              const parsed = JSON.parse(data);

              if (parsed.error) {
                setError(parsed.error);
                setGenerating(false);
                setIsStreaming(false);
                return;
              }

              if (parsed.done && parsed.data) {
                // Streaming complete, set final summary
                setSummary(parsed.data);
                setGenerating(false);
                setIsStreaming(false);
                return;
              }

              if (parsed.content) {
                fullContent += parsed.content;

                // Try to parse JSON incrementally and update sections
                try {
                  // Use brace-depth counting to find the complete JSON object
                  const jsonStart = fullContent.indexOf('{');
                  if (jsonStart !== -1) {
                    let depth = 0;
                    let inString = false;
                    let escaped = false;
                    let jsonEnd = -1;

                    for (let i = jsonStart; i < fullContent.length; i++) {
                      const ch = fullContent[i];
                      if (escaped) { escaped = false; continue; }
                      if (ch === '\\' && inString) { escaped = true; continue; }
                      if (ch === '"') { inString = !inString; continue; }
                      if (inString) continue;
                      if (ch === '{') depth++;
                      else if (ch === '}') {
                        depth--;
                        if (depth === 0) { jsonEnd = i; break; }
                      }
                    }

                    if (jsonEnd > jsonStart) {
                      const jsonObj = JSON.parse(fullContent.substring(jsonStart, jsonEnd + 1));
                      if (jsonObj.strengths) setStreamingStrengths(jsonObj.strengths);
                      if (jsonObj.weaknesses) setStreamingWeaknesses(jsonObj.weaknesses);
                      if (jsonObj.suggestions) setStreamingSuggestions(jsonObj.suggestions);
                      if (jsonObj.discussion_summary) setStreamingDiscussion(jsonObj.discussion_summary);
                      if (jsonObj.overall_summary) setStreamingOverall(jsonObj.overall_summary);
                    }
                  }
                } catch {
                  // JSON not yet complete, continue accumulating
                }
              }
            } catch {
              // Invalid JSON, continue
            }
          }
        }
      }
    } catch (err: any) {
      if (err.name === 'AbortError') {
        // Aborted, do nothing
      } else {
        console.error('Generate error:', err);
        setError('生成学习总结失败，请重试');
      }
      setGenerating(false);
      setIsStreaming(false);
    }
  };

  const qTotal = summary?.question_total ?? 0;
  const qCorrect = summary?.question_correct ?? 0;
  const accuracy = qTotal > 0 ? Math.round((qCorrect / qTotal) * 100) : null;
  const accuracyColor =
    accuracy === null
      ? 'text-gray-400'
      : accuracy >= 80
        ? 'text-green-600'
        : accuracy >= 60
          ? 'text-amber-600'
          : 'text-red-600';

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white border-b border-gray-200 sticky top-0 z-10">
        <div className="max-w-3xl mx-auto px-4 sm:px-6">
          <div className="flex justify-between items-center h-14">
            <div className="flex items-center gap-3">
              <button onClick={() => router.push('/student/chat')} className="text-gray-500 hover:text-gray-700">
                <ArrowLeft className="w-5 h-5" />
              </button>
              <h1 className="text-lg font-bold text-gray-900">学习总结</h1>
            </div>
            <span className="text-sm text-gray-500">{user?.name}</span>
          </div>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-6">
        {loading ? (
          <div className="text-center py-12 text-gray-500">加载中...</div>
        ) : !summary && !isStreaming && !generating && error ? (
          <div className="text-center py-12">
            <AlertCircle className="w-16 h-16 mx-auto mb-4 text-gray-300" />
            <h2 className="text-lg font-medium text-gray-900 mb-2">生成失败</h2>
            <p className="text-red-500 text-sm mb-4">{error}</p>
            <button
              onClick={generateSummary}
              disabled={generating}
              className="px-6 py-2.5 bg-green-600 text-white rounded-lg font-medium hover:bg-green-700 disabled:opacity-50 transition"
            >
              重新生成
            </button>
          </div>
        ) : (
          <div className="space-y-6">
            <div className="flex items-center justify-between">
              <p className="text-sm text-gray-500">
                {summary ? `生成时间: ${new Date(summary.created_at).toLocaleString('zh-CN')}` : '正在生成中...'}
              </p>
              <button
                onClick={generateSummary}
                disabled={generating}
                className="text-sm text-green-600 hover:text-green-700 font-medium disabled:opacity-50"
              >
                {generating ? (
                  <span className="flex items-center gap-1">
                    <Loader2 className="w-3.5 h-3.5 animate-spin" />
                    重新生成中...
                  </span>
                ) : (
                  '重新生成'
                )}
              </button>
            </div>

            {/* 课堂统计 - 仅在已有 summary（非流式中或完成后）显示 */}
            {summary && !isStreaming && (
              <div className="grid grid-cols-3 gap-3">
                <div className="bg-white rounded-xl p-4 border border-gray-100 shadow flex flex-col items-center justify-center">
                  <div className="w-9 h-9 bg-blue-50 rounded-lg flex items-center justify-center mb-2">
                    <ClipboardList className="w-4 h-4 text-blue-600" />
                  </div>
                  <div className="text-2xl font-bold text-gray-900">{qTotal}</div>
                  <div className="text-xs text-gray-500 mt-0.5">答题总数</div>
                </div>
                <div className="bg-white rounded-xl p-4 border border-gray-100 shadow flex flex-col items-center justify-center">
                  <div className="w-9 h-9 bg-green-50 rounded-lg flex items-center justify-center mb-2">
                    <CheckCircle2 className="w-4 h-4 text-green-600" />
                  </div>
                  <div className="text-2xl font-bold text-gray-900">{qCorrect}</div>
                  <div className="text-xs text-gray-500 mt-0.5">答对数</div>
                </div>
                <div className="bg-white rounded-xl p-4 border border-gray-100 shadow flex flex-col items-center justify-center">
                  <div className="w-9 h-9 bg-amber-50 rounded-lg flex items-center justify-center mb-2">
                    <PercentCircle className="w-4 h-4 text-amber-600" />
                  </div>
                  <div className={`text-2xl font-bold ${accuracyColor}`}>
                    {accuracy === null ? '-' : `${accuracy}%`}
                  </div>
                  <div className="text-xs text-gray-500 mt-0.5">正确率</div>
                </div>
              </div>
            )}

            {/* 课堂表现总览 - 突出显示 */}
            <div className="rounded-xl p-6 border border-green-200 shadow bg-gradient-to-br from-green-50 via-white to-emerald-50">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-9 h-9 bg-gradient-to-br from-green-500 to-emerald-600 rounded-lg flex items-center justify-center shadow">
                  <Sparkles className="w-5 h-5 text-white" />
                </div>
                <h3 className="font-semibold text-gray-900">课堂表现总览</h3>
              </div>
              <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">
                {isStreaming ? (streamingOverall || '...') : (summary?.overall_summary || '')}
              </p>
            </div>

            {/* 学习优点 */}
            <div className="bg-white rounded-xl p-6 border border-green-100 shadow">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-8 h-8 bg-green-100 rounded-lg flex items-center justify-center">
                  <ThumbsUp className="w-4 h-4 text-green-600" />
                </div>
                <h3 className="font-semibold text-gray-900">学习优点</h3>
              </div>
              <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">
                {isStreaming ? (streamingStrengths || '...') : (summary?.strengths || '')}
              </p>
            </div>

            {/* 需要改进 */}
            <div className="bg-white rounded-xl p-6 border border-amber-100 shadow">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-8 h-8 bg-amber-100 rounded-lg flex items-center justify-center">
                  <AlertCircle className="w-4 h-4 text-amber-600" />
                </div>
                <h3 className="font-semibold text-gray-900">需要改进</h3>
              </div>
              <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">
                {isStreaming ? (streamingWeaknesses || '...') : (summary?.weaknesses || '')}
              </p>
            </div>

            {/* 进步建议 */}
            <div className="bg-white rounded-xl p-6 border border-blue-100 shadow">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-8 h-8 bg-blue-100 rounded-lg flex items-center justify-center">
                  <Lightbulb className="w-4 h-4 text-blue-600" />
                </div>
                <h3 className="font-semibold text-gray-900">进步建议</h3>
              </div>
              <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">
                {isStreaming ? (streamingSuggestions || '...') : (summary?.suggestions || '')}
              </p>
            </div>

            {/* 小王讨论情况 */}
            <div className="bg-white rounded-xl p-6 border border-purple-100 shadow">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-8 h-8 bg-purple-100 rounded-lg flex items-center justify-center">
                  <Users className="w-4 h-4 text-purple-600" />
                </div>
                <h3 className="font-semibold text-gray-900">小王讨论情况</h3>
              </div>
              <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">
                {isStreaming ? (streamingDiscussion || '...') : (summary?.discussion_summary || '')}
              </p>
            </div>

            {summary && !isStreaming && (
              <div className="text-center">
                <button
                  onClick={() => router.push('/student/chat')}
                  className="px-6 py-2.5 bg-gray-100 text-gray-700 rounded-lg font-medium hover:bg-gray-200 transition"
                >
                  继续学习
                </button>
              </div>
            )}
          </div>
        )}
      </main>
    </div>
  );
}

export default function SummaryPage() {
  return (
    <Suspense fallback={<div className="flex items-center justify-center min-h-screen"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-emerald-500" /></div>}>
      <StudentSummaryContent />
    </Suspense>
  );
}
